{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.existingSecretName | quote }}
type: Opaque
stringData:
  client-id: {{ .Values.auth.clientID | quote }}
  client-secret: {{ .Values.auth.clientSecret | quote }}
  cookie-secret: {{ .Values.auth.cookieSecret | quote }}
{{- end }}
